---
title: Mark Pollard
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: article
  resources:
    title: Resources
    output: true
    permalink: "/resources/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: article
    summary: 
    image: 
- scope:
    path: ''
    type: resources
  values:
    layout: article
    summary: 
    image: 
- scope:
    path: ''
    type: pages
  values:
    summary: 
    image: 
    categories: 
name: Mark Pollard
description: Strategy is Your Words
google_analytics: UA-6991341-1
repository: markhpollard/markhpollard.github.io
promotext: The "Strategy Is Your Words" book Kickstarter blew past its goal within
  48 hours. Thank you so much for your support. Expect it in May 2020. Sign up to
  the newsletter for updates.
promolink: https://www.markpollard.net/email-newsletter/
url: 
baseurl: 
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: expanded
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
