---
title: Mark Pollard
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    layout: article
  resources:
    title: Resources
    output: true
    permalink: "/resources/:title"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
   type: "posts"
  values:
   layout: "article"
   summary:
name: Mark Pollard
description: Strategy is Your Words
google_analytics: UA-91441149-1
url:
baseurl:
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
